### ISSUE TITLE
logo.py 제작

### ISSUE THREAD

**Issue by habby9000** [Ramenseller/RedList#10]
print_logo함수 : 로고 프린트

main.py실행 시 로고 띄우고 시작

**Comment by hy-kiera** [comment]
#6 에서 로고, 제품명을 정한 것을 프린트할 수 있게 하면 좋을거 같아요!

**Comment by hy-kiera** [comment]
저희 팀이랑 팀원 정보도 추가하면 어떨까요?

**Comment by ujma1234** [comment]
제작자랑 간단한 설명을 넣는 것도 좋을 것 같네요
