### ISSUE TITLE
UI개선과 기능개선

### ISSUE THREAD

**Issue by ujma1234** [Ramenseller/RedList#44]
- [ ]  table디자인 (중요도는 별모양, 한눈에 볼 수 있는 table, 띄어쓰기 정렬)

- [ ]  기한이 지난 todo도 list에서 선택할 수 있게하기

- [ ]  modify 에서 what이 아닌 id로 선택 ( what은 이름이 중복될 시  선입력된 todo만 수정가능)

- [ ] list에서 id도 보여주기

**Comment by hy-kiera** [comment]
글자 색 참고 : https://github.com/tartley/colorama

**Comment by ujma1234** [comment]
넵
