### ISSUE TITLE
Name and Logo

### ISSUE THREAD

**Issue by hy-kiera** [Ramenseller/RedList#6]
우리 팀의 todolist 이름과 그 이름을 ascii art로 logo를 만들어서 밑 코멘트로 달아주세요. thum-up으로 투표하면 좋을 것 같습니다.(중복투표ok)

**Comment by Ramenseller** [comment]
RedList
Redhat사의 팀들 중 하나로 일한다는 전제니깐 Red 붙이면 좋을듯 하네요

**Comment by Goodkorning** [comment]
[logos.txt](https://github.com/Ramenseller/B4_OS18/files/2011453/logos.txt)
